### ISSUE TITLE
Twitter API v2.0

### ISSUE THREAD

**Issue by snus-kin** [snus-kin/twitter.nim#3]
Twitter announced a V2 API we should begin looking at this

No hard spec has been released but this should ideally be done in a branch as spec is finalised

**Comment by snus-kin** [comment]
labs for v2 [here](https://developer.twitter.com/en/docs/labs/overview/introduction), will look at trying to implement this generally as possible to start with then individual endpoints

**Comment by andypiper** [comment]
V2 is basically the same as current Labs. OAuth has not changed but the call endpoints, params and output formats are very new. Should be live very soon. Thanks!

**Comment by snus-kin** [comment]
wonderful thanks for the info just haven't gotten around to reading anything about it yet. good luck with the launch :)

**Comment by snus-kin** [comment]
v2 api reference index
https://developer.twitter.com/en/docs/api-reference-index#twitter-api-v2

**Comment by Patitotective** [comment]
Is API v2.0 support going to be released soon? I'd really like to use this library :upside_down_face: .

**Comment by snus-kin** [comment]
I've not really thought about this for a while, been quite busy with my degree. Am free now though, I think maybe I can start having a look and see how feasible it might be.

**Comment by snus-kin** [comment]
I can probably get started on this tomorrow, was thinking of how to structure the actual calls, a lot of libraries have a `api.v2.endpoint` type structure but not 100% sure how I'd achieve this... seems like most of the bearer token authenticated endpoints should work right now by using the low-level `get` and `post` methods.

**Comment by andypiper** [comment]
When I originally commented above, OAuth 2.0 support was not yet available - that’s now the preferred authentication method (although some endpoints may still support OAuth 1.0A)

**Comment by snus-kin** [comment]
Hey I think all the endpoints are there in the v2 branch 

@andypiper am I right in thinking that access to all of the `oauth2/` endpoints and being able to send requests with a bearer token is everything for OAuth2? Thanks

**Comment by andypiper** [comment]
You’ll also need to be able to do user authentication with OAuth 2 and to specify scopes, as well as handling refresh tokens. I haven’t looked at the implementation here, just picked up that there was some conversation on this issue :-) great that you have the endpoints implemented. You may want to head over to the [developer forums](https://twittercommunity.com) if you have specific authentication API questions.
